# Generated by Django 5.1 on 2024-09-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_cooking_time_remove_recipe_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=200)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
